### ISSUE TITLE
Create sumNumbersOfCollection(int positionOfNumberToSum1, int positionOfNumberToSum2) for DecimalCollection

### ISSUE THREAD

**Issue by egraciani** [egraciani/IWVG.SwC.egraciani#6]
El objetivo es crear el método sumNumbersOfCollection(int positionOfNumberToSum1, int positionOfNumberToSum2) para la clase DecimalCollection. Este método devuelve la suma de los numeros que se encuentren en las posiciones positionOfNumberToSum1 y positionOfNumberToSum2 de DecimalCollection (e.g. decimalCollection = [1,1,3,4,5]. Entonces sumNumbersOfCollection(2, 4) devuelve 5 porque sumará 1+4. Para más info ver wiki.

**Comment by egraciani** [comment]
Resolver en issue#06

**Comment by DavidBlasVazquez** [comment]
Esta subida la rama y fusionada con develop.
Un saludo.

El 26/9/2017 23:09, "egraciani" <notifications@github.com> escribió:

Assigned #6 <https://github.com/egraciani/IWVG.SwC.egraciani/issues/6> to
@DavidBlasVazquez <https://github.com/davidblasvazquez>.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/egraciani/IWVG.SwC.egraciani/issues/6#event-1266617396>,
or mute the thread
